on: ["pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 20.10
      uses: actions/setup-node@v4
      with:
        node-version: 20.10

    - name: npm install, test-coverage
      run: |
        echo "email=${{secrets.REGISTRY_EMAIL}}" > ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
        echo "@<SCOPE>:registry=${{secrets.REGISTRY_URL}}" >> ~/.npmrc
        echo "//lpg.jfrog.io/artifactory/api/npm/virt-lpg-npm/:_password=${{secrets.REGISTRY_PASSWORD}}" >> ~/.npmrc
        echo "//lpg.jfrog.io/artifactory/api/npm/virt-lpg-npm/:username=${{secrets.REGISTRY_EMAIL}}" >> ~/.npmrc
        echo "//registry.npmjs.org/:username=${{secrets.REGISTRY_EMAIL}}" >> ~/.npmrc
        echo "//registry.npmjs.org/:_password=${{secrets.REGISTRY_PASSWORD}}" >> ~/.npmrc
        echo "registry=${{secrets.REGISTRY_URL}}" >> ~/.npmrc
        npm install
        npm run test -- --coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
